POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTkzMzgzLCJleHAiOjE3NDI5OTY5ODN9.n3ixqLPMOnOxG4A4LxonrJderfQMa2P3TqSIcIgG12c
{
  "productId": 5,
  "quantity": 2
}


GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTgyNzk5LCJleHAiOjE3NDI5ODYzOTl9.4wMMlX9Za_3AIyw6yS8GyWcvI5afVu20lklHe7fChOM

DELETE http://localhost:3000/cart/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTgyNzk5LCJleHAiOjE3NDI5ODYzOTl9.4wMMlX9Za_3AIyw6yS8GyWcvI5afVu20lklHe7fChOM