POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTc5OTYxLCJleHAiOjE3NDI5ODM1NjF9.9Vaye0BTYKaLybF0t3tb1aX1Biw9szgxVNTVnfPaHVA
{
  "productId": 5,
  "quantity": 2
}


GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTgyNzk5LCJleHAiOjE3NDI5ODYzOTl9.4wMMlX9Za_3AIyw6yS8GyWcvI5afVu20lklHe7fChOM

DELETE http://localhost:3000/cart/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTgyNzk5LCJleHAiOjE3NDI5ODYzOTl9.4wMMlX9Za_3AIyw6yS8GyWcvI5afVu20lklHe7fChOM