POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTk0NzU1LCJleHAiOjE3NDI5OTgzNTV9.RX-1MHAA8-ch_ZaOp4xO-WGZVScQz-cZNzKzF-CPk30
{
  "productId": 5,
  "quantity": 12
}


GET http://localhost:3000/cart
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTk0NzU1LCJleHAiOjE3NDI5OTgzNTV9.RX-1MHAA8-ch_ZaOp4xO-WGZVScQz-cZNzKzF-CPk30

DELETE http://localhost:3000/cart/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTk0NzU1LCJleHAiOjE3NDI5OTgzNTV9.RX-1MHAA8-ch_ZaOp4xO-WGZVScQz-cZNzKzF-CPk30