POST http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3NTM2LCJleHAiOjE3NDUzNTExMzZ9.17M0yPhTP8bbsE2QozYOc6uZfzt5KAI-6JLK4Mjn92U

GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3NTM2LCJleHAiOjE3NDUzNTExMzZ9.17M0yPhTP8bbsE2QozYOc6uZfzt5KAI-6JLK4Mjn92U

GET http://localhost:3000/orders/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3NTM2LCJleHAiOjE3NDUzNTExMzZ9.17M0yPhTP8bbsE2QozYOc6uZfzt5KAI-6JLK4Mjn92U

PATCH http://localhost:3000/orders/1/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3NTM2LCJleHAiOjE3NDUzNTExMzZ9.17M0yPhTP8bbsE2QozYOc6uZfzt5KAI-6JLK4Mjn92U
Content-Type: application/json

{
  "status": "paid"
}

PATCH http://localhost:3000/orders/2/pay
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3NTM2LCJleHAiOjE3NDUzNTExMzZ9.17M0yPhTP8bbsE2QozYOc6uZfzt5KAI-6JLK4Mjn92U
Content-Type: application/json