POST http://localhost:3000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3ODk0LCJleHAiOjE3NDUzNTE0OTR9.g0dZqBjnf_pJk6HXN7vpPcEkCzxakSE-7F9dtpjBOZQ
{
  "name": "Laptop",
  "description": "Lightweight running shoes",
  "price": 99.99,
  "stock": 25,
  "imageUrl": "https://picsum.photos/300",
    "categoryId": 1
}

GET http://localhost:3000/products

GET http://localhost:3000/products?page=1&limit=2

GET http://localhost:3000/products/2

DELETE http://localhost:3000/products/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MzQ3ODk0LCJleHAiOjE3NDUzNTE0OTR9.g0dZqBjnf_pJk6HXN7vpPcEkCzxakSE-7F9dtpjBOZQ

GET  http://localhost:3000/products/category/1
