GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQyOTU3ODYwLCJleHAiOjE3NDI5NjE0NjB9.YiNSTYXBGQleZgy9OT5uLLsXJkvp2YYbI7DilFOzQaI
