POST http://localhost:3000/wishlist/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MjA3OTE1LCJleHAiOjE3NDUyMTE1MTV9.MV7pYhUB7aM1ZPJz40PlTKefIp1jtYvON3_rS56xEHI

GET http://localhost:3000/wishlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MjA3OTE1LCJleHAiOjE3NDUyMTE1MTV9.MV7pYhUB7aM1ZPJz40PlTKefIp1jtYvON3_rS56xEHI

DELETE http://localhost:3000/wishlist/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzQ1MjA3OTE1LCJleHAiOjE3NDUyMTE1MTV9.MV7pYhUB7aM1ZPJz40PlTKefIp1jtYvON3_rS56xEHI